version: '3.8'

services:
  classifier_daemon:
    build: .
    container_name: email_daemon
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: python src/main.py

  streamlit_dashboard:
    build: .
    container_name: email_dashboard
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: streamlit run src/dashboard.py --server.address=0.0.0.0
